### PR TITLE
Migration initial accounts and roles

### PR DESCRIPTION
**Pull request by axelra82**
During a local reboot (deleted repo and fresh clone from repo) I realized that we need to setup at least one initial default admin in our migration when we create the user table (otherwise there is no user that can grant other users admin status 🤪). Since one of the passing requirements was that we should handle the database through migrations our best option is to create what we need in the initial migration 👍 

~~I've updated our users (`2014_10_12_000000_create_users_table.php`) and permissions (`2021_02_17_140407_create_permission_tables.php`) migrations to include:~~

I've added a seeder (`database\seeders\UserSeeder.php`) that will add the following to the database:
- one **admin** user (`admin@admin.com` `secret`)
- one (regular) **user** (`user@user.com` `secret`)
- Roles `admin` and `user` attached to respective user with permissions

Use `php artisan db:seed --class=UserSeeder` to run seeder.

### CODE REVIEW

**Review by stenwall — APPROVED** [review]
🎉

**Review by johannasjo — APPROVED** [review]
LGTM!

**Comment by axelra82** [comment]
Since I posted this during a weekend I'll hold of 'till tomorrow so everyone has a chance to report back/test it 😄

I plan on merging this to main tomorrow before lunch if no one has reported back before then 😉

**Review by VeronicaT78 — APPROVED** [review]
ok

**Pull request merged**
