### PR TITLE
New classes for buttons

### PR DESCRIPTION
**Pull request by stenwall**
I've added some new classes so that our buttons to match the rest of the color scheme. These classes are supposed to (and should, if you all agree 😊 ) be used instead of Bootstrap's classes `btn-primary` and  `btn-secondary`.
(Note that the basic button-class `btn`  still need to be used.)

I also threw in some structure to the main- and color-scss-files, and added some new variables.

Hope you all like it! 🌞

### CODE REVIEW

**Comment by stenwall** [comment]
Not sure why deployment fails to build after I've added the secure-asset?

Do you have any clue, @johannasjo  @axelra82 ?

**Comment by johannasjo** [comment]
> Not sure why deployment fails to build after I've added the secure-asset?
> 
> Do you have any clue, @johannasjo @axelra82 ?

I think it's because it should be secure_asset, try it and let's hope that's it :)

**Comment by stenwall** [comment]
> I think it's because it should be secure_asset, try it and let's hope that's it :)

Deployment is working now! 🥳 
I also changed to `secure_asset`, hopefully no more conflicts or problems...

**Comment by axelra82** [comment]
As @johannasjo mentioned, check secure_assets (vs assets). This should always be secure_assets now since we are almost done with local HTTPS for everyone.

I believe we looked at this during the morning standup (with the faulty sass variable in the build log).

@stenwall Have you looked at [bootstrap theming](https://getbootstrap.com/docs/4.0/getting-started/theming/)? 🤔 That would allow for using the standard bootstrap names (e.g. `btn-primary`, `btn-secondary`) but get it to look the way you want 😉

**Comment by stenwall** [comment]
> As @johannasjo mentioned, check secure_assets (vs assets). This should always be secure_assets now since we are almost done with local HTTPS for everyone.

Yes, this is resolved now!

> @stenwall Have you looked at [bootstrap theming](https://getbootstrap.com/docs/4.0/getting-started/theming/)? 🤔 That would allow for using the standard bootstrap names (e.g. `btn-primary`, `btn-secondary`) but get it to look the way you want 😉

If everyone is okay with the new button-design, I could do that instead! Easier to remember too 😉 

**EDIT**: Does the theming work with Bootstrap 5.0 though?

**Comment by johannasjo** [comment]
> > @stenwall Have you looked at [bootstrap theming](https://getbootstrap.com/docs/4.0/getting-started/theming/)? 🤔 That would allow for using the standard bootstrap names (e.g. `btn-primary`, `btn-secondary`) but get it to look the way you want 😉
> 
> If everyone is okay with the new button-design, I could do that instead! Easier to remember too 😉
> 
> **EDIT**: Does the theming work with Bootstrap 5.0 though?

I agree with this if it's possible!

**Review by johannasjo — COMMENTED** [review]
LGTM!

**Pull request merged**
